repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        language_version: python3
        minimum_pre_commit_version: 2.9.2